// The main character's sprite strips. Every strip is rendered from the rig (anglerRig.js →
// anglerDraw.js) for whatever look the angler wears; the PNGs imported here are that same
// renderer's output for the default look — regenerated by `node scripts/renderAnglerSheets.mjs`
// whenever the rig or the drawing changes — and show wherever a strip can't be drawn
// (no canvas) or hasn't been drawn yet. Every frame sits in the same box with the feet
// anchored at (feetX, feetY) so actions can swap without the figure hopping.
import idle from '../assets/angler/idle.png';
import cast from '../assets/angler/cast.png';
import reel from '../assets/angler/reel.png';
import fishon from '../assets/angler/fishon.png';
import celebrate from '../assets/angler/celebrate.png';
import { SPRITE_FRAME, FRAME_COUNTS, rodTipFor } from './anglerRig';

export { SPRITE_FRAME };

const STOCK = { idle, cast, reel, fishon, celebrate };

// rodTip is where the line leaves the rod for that strip's held pose, in frame pixels.
export const ANGLER_SPRITES = Object.fromEntries(Object.keys(FRAME_COUNTS).map((action) => [action, { src: STOCK[action], frames: FRAME_COUNTS[action], rodTip: rodTipFor(action) }]));

// What the angler is doing in each phase: which strip, how many frames to step through, and
// whether it plays once (forwards) or loops. `holding` only matters while reeling — the loop
// runs while the player is actually cranking, so nothing animates on its own.
export function anglerAction({ phase, result, holding }) {
  switch (phase) {
    case 'casting': return { action: 'cast', play: 6, durationMs: 600 };
    case 'waiting': return { action: 'cast', frame: 5 };
    case 'hookset': return { action: 'fishon', play: 6, durationMs: 450 };
    case 'reeling': return holding ? { action: 'reel', play: 7, durationMs: 700, loop: true } : { action: 'reel', frame: 0 };
    case 'result': return result?.success ? { action: 'celebrate', play: 4, durationMs: 500 } : { action: 'idle', frame: 0 };
    default: return { action: 'idle', frame: 0 };
  }
}
