import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from './context/AuthContext';
import FishIllustration from './components/FishIllustration';
import HookIcon from './components/HookIcon';

export default function Home() {
  const { profile } = useAuth();
  const name = profile.display_name?.split(' ')[0] || 'angler';
  return <main className="content-shell home-page"><section className="welcome-banner"><div><span className="eyebrow">DOCK REPORT · SEPT 5</span><h1>Look who dragged themselves in, {name}.</h1><p>Somebody in this crew is about to beat your best fish this month. Don't let it be Kevin.</p><div className="hero-actions"><Link className="button button-primary" to="/fish-year">Log this month <span>→</span></Link><Link className="text-link" to="/profile">Still ghosting your profile? ↗</Link></div></div><div className="fishing-scene" aria-hidden="true"><span className="lure-line" /><HookIcon className="lure-hook" /><div className="scene-fish scene-fish-back"><FishIllustration species="bass" /><span className="scene-fish-tag">Bass</span></div><div className="scene-fish scene-fish-front"><FishIllustration species="pike" /><span className="scene-fish-tag">Pike</span></div></div></section><section className="dashboard-grid"><article className="feature-card feature-card-dark"><div className="card-topline"><span className="eyebrow">LIVE SEASON</span><span className="status-badge">OPEN</span></div><h2>Fish Year<br /><em>2026</em></h2><p>One fish a month, no excuses. Don't be the guy who skips April.</p><div className="tally-row" aria-hidden="true">{Array.from({ length: 12 }).map((_, index) => <span key={index} className={index < 2 ? 'tally-filled' : 'tally-empty'} />)}</div><div className="card-footer"><span>2 / 12 months logged</span><Link to="/fish-year">See where you stand →</Link></div></article><article className="feature-card feature-card-light"><div className="card-topline"><span className="eyebrow">LAST SEASON</span><span className="card-icon">↗</span></div><h2>Fluke<br /><em>Tournament</em></h2><p>Andre's still rubbing his 20-inch fluke in everyone's face. Somebody dethrone him.</p><div className="card-footer"><span>20 in · 1st place</span><Link to="/fluke-tournament">Come see the proof →</Link></div></article></section><section className="dock-notes"><div className="section-heading"><div><span className="eyebrow">CREW LOG</span><h2>What you've been slacking on</h2></div></div><div className="notes-board"><Link className="note-card note-card-one" to="/profile"><span className="note-pin" /><strong>Your profile's a ghost town</strong><p>Tell the crew your home water before they assume you fish from a bathtub.</p><span className="note-go">Fix it →</span></Link><Link className="note-card note-card-two" to="/fish-year"><span className="note-pin" /><strong>You haven't peeked at the board</strong><p>See who's ahead on Fish Year before someone starts talking trash about you.</p><span className="note-go">Take a look →</span></Link></div></section></main>;
}
