import React, { useState } from 'react';
import { useAuth } from './context/AuthContext';

export default function Profile() {
  const { user, profile, updateProfile, signOut, notice, setNotice } = useAuth();
  const [form, setForm] = useState(profile);
  const [saved, setSaved] = useState(false);
  async function saveProfile(event) { event.preventDefault(); await updateProfile(form); setSaved(true); setTimeout(() => setSaved(false), 2200); }
  return <main className="content-shell profile-page"><div className="page-intro"><span className="eyebrow">YOUR PROFILE</span><h1>Make it yours.</h1><p>Give the crew a little context before the next tide.</p></div><section className="profile-layout"><aside className="profile-card"><div className="avatar avatar-large">{(form.display_name || 'N').slice(0, 1).toUpperCase()}</div><h2>{form.display_name || 'New angler'}</h2><p>{user?.email}</p><div className="profile-tag">Member since 2025</div><button className="button button-quiet" type="button" onClick={signOut}>Sign out</button></aside><form className="settings-card" onSubmit={saveProfile}><div className="section-heading"><div><span className="eyebrow">PROFILE DETAILS</span><h2>How should we know you?</h2></div><span className="status-dot">● Saved privately</span></div><label>Display name<input value={form.display_name || ''} onChange={(e) => setForm({ ...form, display_name: e.target.value })} /></label><label>Home water<input value={form.home_water || ''} onChange={(e) => setForm({ ...form, home_water: e.target.value })} placeholder="Bay, river, lake, or coastline" /></label><label>Favorite species<input value={form.favorite_species || ''} onChange={(e) => setForm({ ...form, favorite_species: e.target.value })} placeholder="Striped bass, fluke..." /></label><label>About you<textarea rows="4" value={form.bio || ''} onChange={(e) => setForm({ ...form, bio: e.target.value })} placeholder="A sentence about how you fish" /></label><div className="form-actions"><button className="button button-primary" type="submit">Save profile <span>→</span></button>{saved && <span className="saved-message">Profile updated</span>}</div>{notice && <p className="preview-note">{notice}<button type="button" onClick={() => setNotice('')}>Dismiss</button></p>}</form></section></main>;
}